sonar.projectKey=codescan-mcp-server
sonar.organization=presh-ar
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,jest.config.js,eslint.config.js
sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=**/*.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
